# Site settings
title: Jonathan Johnson
email: jon.johnson@ucsf.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal site and playground for Jonathan Johnson a web developer working
  on the Ilios Project at the UC San Francisco Library in the Center
  for Knowledge Management and Living in Pacifica, CA
baseurl: ""
url: "https://jrjohnson.github.io"
twitter_username: iam_jrjohnson
github_username:  jrjohnson

# Build settings
markdown: kramdown
collections:
  talks:
    output: true
